### ISSUE TITLE
Get a beer recommended 

### ISSUE THREAD

**Issue by dammalex3** [dammalex3/project1#4]
### User Story
As a user, I want to be recommended a new beer of a particular stye so that I can try it.

### Acceptance Criteria
- [ ] Display beer styles on the UI
- [ ] When a style is selected by the user, a beer of that style is recommended

### Tasks
- [ ] Display clickable beer styles with images
- [ ] When beer style is selected, call API with that style to get the beer
- [ ] Pick a random result from the API response
